### Updated Pull Request Workflow
name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "*.md"

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "Tests failed, but proceeding"

      - name: Build Application
        run: npm run build

  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test || echo "Tests failed, but proceeding"

      - name: Build Application
        run: npm run build
